#
# Software Name : towards5gs-helm-nat
# SPDX-FileCopyrightText: Copyright (c) 2022 TU Darmstadt
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Tobias MEUSER
# Software description: A simple linux-based NAT implementation to complement free5gc
#
{{- with .Values.nat }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-nat.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-nat.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-nat.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-nat.natAnnotations" $ | nindent 8 }}
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ $.Values.global.n6network.name }}-{{ include "free5gc-nat.fullname" $ }}",
              "interface": "n6",
              "ips": [ "{{ .n6if.ipAddress }}/{{ $.Values.global.n6network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n6network.gatewayIP }}" ]
            }
            ]'
        checksum/config: {{ include (print $.Template.BasePath "/nat-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-nat.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["{{ .volume.mount }}/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0777
{{- end }}