#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "single" }}
{{- with .Values.upf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.global.projectName }}
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      {{- toYaml .configuration.configuration | nindent 6 }}
    
      pfcp:
        - addr: {{ .n4if.ipAddress }}
    
      gtpu:
        - addr: {{ .n3if.ipAddress }}
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
{{- if eq $.Values.global.networkAccessTranslation "separated" }}
  wrapper.sh: |
    #!/bin/sh

    ### Implement networking rules
    sysctl -w net.ipv4.ip_forward=1
    
    ip route del default
    ip route add default via {{ $.Values.global.n6network.gatewayIP }} dev n6  # add a default route in the created table so that all UEs will use this gateway for external communications (target IP not in the Data Network attached to the interface N6) and then the Data Network will manage to route the traffic

    /free5gc/free5gc-upfd/free5gc-upfd -c {{ .volume.mount }}/upfcfg.yaml
{{- else }}
  wrapper.sh: |
    #!/bin/sh

    ### Implement networking rules
    sysctl -w net.ipv4.ip_forward=1
    
    iptables -I FORWARD 1 -j ACCEPT
    iptables -t nat -A POSTROUTING -s {{ $.Values.global.uesubnet }} -o eth0 -j MASQUERADE

    /free5gc/free5gc-upfd/free5gc-upfd -c {{ .volume.mount }}/upfcfg.yaml
{{- end }}
{{- end }}
{{- end }}
